// sequences of triplets

var sequences = [

// ek mukta devanagari: triplet combinations of ['bha', 'ddha', 'e', 'ja', 'ka', 'ma', 'na', 'sha'], total: 56
['ek-mukta_devanagari', 'https://getform.org/f/0915f671-31db-4375-9197-5b3c69858164', [['bha', 'ma', 'na'], ['bha', 'ka', 'na'], ['bha', 'ja', 'na'], ['bha', 'ddha', 'na'], ['bha', 'na', 'sha'], ['bha', 'e', 'na'], ['ka', 'ma', 'na'], ['ja', 'ma', 'na'], ['ddha', 'ma', 'na'], ['ma', 'na', 'sha'], ['e', 'ma', 'na'], ['ja', 'ka', 'na'], ['ddha', 'ka', 'na'], ['ka', 'na', 'sha'], ['e', 'ka', 'na'], ['ddha', 'ja', 'na'], ['ja', 'na', 'sha'], ['e', 'ja', 'na'], ['ddha', 'na', 'sha'], ['ddha', 'e', 'na'], ['e', 'na', 'sha'], ['bha', 'ka', 'ma'], ['bha', 'ja', 'ma'], ['bha', 'ddha', 'ma'], ['bha', 'ma', 'sha'], ['bha', 'e', 'ma'], ['bha', 'ja', 'ka'], ['bha', 'ddha', 'ka'], ['bha', 'ka', 'sha'], ['bha', 'e', 'ka'], ['bha', 'ddha', 'ja'], ['bha', 'ja', 'sha'], ['bha', 'e', 'ja'], ['bha', 'ddha', 'sha'], ['bha', 'ddha', 'e'], ['bha', 'e', 'sha'], ['ja', 'ka', 'ma'], ['ddha', 'ka', 'ma'], ['ka', 'ma', 'sha'], ['e', 'ka', 'ma'], ['ddha', 'ja', 'ma'], ['ja', 'ma', 'sha'], ['e', 'ja', 'ma'], ['ddha', 'ma', 'sha'], ['ddha', 'e', 'ma'], ['e', 'ma', 'sha'], ['ddha', 'ja', 'ka'], ['ja', 'ka', 'sha'], ['e', 'ja', 'ka'], ['ddha', 'ka', 'sha'], ['ddha', 'e', 'ka'], ['e', 'ka', 'sha'], ['ddha', 'ja', 'sha'], ['ddha', 'e', 'ja'], ['e', 'ja', 'sha'], ['ddha', 'e', 'sha']]] ,

// lohit devanagari devanagari: triplet combinations of ['ga', 'ka', 'la', 'nna', 'pa', 'pha', 'tha', 'ya'], total: 56
['lohit-devanagari_devanagari', 'https://getform.org/f/43366603-58e4-4d58-b693-ebb799795f0f', [['nna', 'pa', 'pha'], ['nna', 'pa', 'tha'], ['nna', 'pa', 'ya'], ['ka', 'nna', 'pa'], ['la', 'nna', 'pa'], ['ga', 'nna', 'pa'], ['nna', 'pha', 'tha'], ['nna', 'pha', 'ya'], ['ka', 'nna', 'pha'], ['la', 'nna', 'pha'], ['ga', 'nna', 'pha'], ['nna', 'tha', 'ya'], ['ka', 'nna', 'tha'], ['la', 'nna', 'tha'], ['ga', 'nna', 'tha'], ['ka', 'nna', 'ya'], ['la', 'nna', 'ya'], ['ga', 'nna', 'ya'], ['ka', 'la', 'nna'], ['ga', 'ka', 'nna'], ['ga', 'la', 'nna'], ['pa', 'pha', 'tha'], ['pa', 'pha', 'ya'], ['ka', 'pa', 'pha'], ['la', 'pa', 'pha'], ['ga', 'pa', 'pha'], ['pa', 'tha', 'ya'], ['ka', 'pa', 'tha'], ['la', 'pa', 'tha'], ['ga', 'pa', 'tha'], ['ka', 'pa', 'ya'], ['la', 'pa', 'ya'], ['ga', 'pa', 'ya'], ['ka', 'la', 'pa'], ['ga', 'ka', 'pa'], ['ga', 'la', 'pa'], ['pha', 'tha', 'ya'], ['ka', 'pha', 'tha'], ['la', 'pha', 'tha'], ['ga', 'pha', 'tha'], ['ka', 'pha', 'ya'], ['la', 'pha', 'ya'], ['ga', 'pha', 'ya'], ['ka', 'la', 'pha'], ['ga', 'ka', 'pha'], ['ga', 'la', 'pha'], ['ka', 'tha', 'ya'], ['la', 'tha', 'ya'], ['ga', 'tha', 'ya'], ['ka', 'la', 'tha'], ['ga', 'ka', 'tha'], ['ga', 'la', 'tha'], ['ka', 'la', 'ya'], ['ga', 'ka', 'ya'], ['ga', 'la', 'ya'], ['ga', 'ka', 'la']]] ,

// adobe devanagari devanagari: triplet combinations of ['a', 'ba', 'gha', 'kha', 'ra', 'sa', 'ssa', 'ta'], total: 56
['adobe-devanagari_devanagari', 'https://getform.org/f/517b5c2c-e726-4cec-bb12-6eebbb755eed', [['ra', 'sa', 'ta'], ['kha', 'ra', 'ta'], ['ba', 'ra', 'ta'], ['a', 'ra', 'ta'], ['gha', 'ra', 'ta'], ['ra', 'ssa', 'ta'], ['kha', 'sa', 'ta'], ['ba', 'sa', 'ta'], ['a', 'sa', 'ta'], ['gha', 'sa', 'ta'], ['sa', 'ssa', 'ta'], ['ba', 'kha', 'ta'], ['a', 'kha', 'ta'], ['gha', 'kha', 'ta'], ['kha', 'ssa', 'ta'], ['a', 'ba', 'ta'], ['ba', 'gha', 'ta'], ['ba', 'ssa', 'ta'], ['a', 'gha', 'ta'], ['a', 'ssa', 'ta'], ['gha', 'ssa', 'ta'], ['kha', 'ra', 'sa'], ['ba', 'ra', 'sa'], ['a', 'ra', 'sa'], ['gha', 'ra', 'sa'], ['ra', 'sa', 'ssa'], ['ba', 'kha', 'ra'], ['a', 'kha', 'ra'], ['gha', 'kha', 'ra'], ['kha', 'ra', 'ssa'], ['a', 'ba', 'ra'], ['ba', 'gha', 'ra'], ['ba', 'ra', 'ssa'], ['a', 'gha', 'ra'], ['a', 'ra', 'ssa'], ['gha', 'ra', 'ssa'], ['ba', 'kha', 'sa'], ['a', 'kha', 'sa'], ['gha', 'kha', 'sa'], ['kha', 'sa', 'ssa'], ['a', 'ba', 'sa'], ['ba', 'gha', 'sa'], ['ba', 'sa', 'ssa'], ['a', 'gha', 'sa'], ['a', 'sa', 'ssa'], ['gha', 'sa', 'ssa'], ['a', 'ba', 'kha'], ['ba', 'gha', 'kha'], ['ba', 'kha', 'ssa'], ['a', 'gha', 'kha'], ['a', 'kha', 'ssa'], ['gha', 'kha', 'ssa'], ['a', 'ba', 'gha'], ['a', 'ba', 'ssa'], ['ba', 'gha', 'ssa'], ['a', 'gha', 'ssa']]] ,

// nirmala ui devanagari: triplet combinations of ['cha', 'da', 'dha', 'la', 'nga', 'tta', 'ttha', 'u'], total: 56
['nirmala-ui_devanagari', 'https://getform.org/f/9f49e10b-a573-4d86-bbaa-cc903297e4ee', [['da', 'tta', 'ttha'], ['tta', 'ttha', 'u'], ['cha', 'tta', 'ttha'], ['dha', 'tta', 'ttha'], ['nga', 'tta', 'ttha'], ['la', 'tta', 'ttha'], ['da', 'tta', 'u'], ['cha', 'da', 'tta'], ['da', 'dha', 'tta'], ['da', 'nga', 'tta'], ['da', 'la', 'tta'], ['cha', 'tta', 'u'], ['dha', 'tta', 'u'], ['nga', 'tta', 'u'], ['la', 'tta', 'u'], ['cha', 'dha', 'tta'], ['cha', 'nga', 'tta'], ['cha', 'la', 'tta'], ['dha', 'nga', 'tta'], ['dha', 'la', 'tta'], ['la', 'nga', 'tta'], ['da', 'ttha', 'u'], ['cha', 'da', 'ttha'], ['da', 'dha', 'ttha'], ['da', 'nga', 'ttha'], ['da', 'la', 'ttha'], ['cha', 'ttha', 'u'], ['dha', 'ttha', 'u'], ['nga', 'ttha', 'u'], ['la', 'ttha', 'u'], ['cha', 'dha', 'ttha'], ['cha', 'nga', 'ttha'], ['cha', 'la', 'ttha'], ['dha', 'nga', 'ttha'], ['dha', 'la', 'ttha'], ['la', 'nga', 'ttha'], ['cha', 'da', 'u'], ['da', 'dha', 'u'], ['da', 'nga', 'u'], ['da', 'la', 'u'], ['cha', 'da', 'dha'], ['cha', 'da', 'nga'], ['cha', 'da', 'la'], ['da', 'dha', 'nga'], ['da', 'dha', 'la'], ['da', 'la', 'nga'], ['cha', 'dha', 'u'], ['cha', 'nga', 'u'], ['cha', 'la', 'u'], ['dha', 'nga', 'u'], ['dha', 'la', 'u'], ['la', 'nga', 'u'], ['cha', 'dha', 'nga'], ['cha', 'dha', 'la'], ['cha', 'la', 'nga'], ['dha', 'la', 'nga']]] ,

// itf devanagari devanagari: triplet combinations of ['bha', 'ca', 'jha', 'ma', 'nya', 'ra', 'ttha', 'va'], total: 56
['itf-devanagari_devanagari', 'https://getform.org/f/3ccb2845-bf53-45af-b7bd-9007f1f20680', [['ca', 'nya', 'va'], ['bha', 'ca', 'nya'], ['ca', 'ma', 'nya'], ['ca', 'jha', 'nya'], ['ca', 'nya', 'ra'], ['ca', 'nya', 'ttha'], ['bha', 'ca', 'va'], ['ca', 'ma', 'va'], ['ca', 'jha', 'va'], ['ca', 'ra', 'va'], ['ca', 'ttha', 'va'], ['bha', 'ca', 'ma'], ['bha', 'ca', 'jha'], ['bha', 'ca', 'ra'], ['bha', 'ca', 'ttha'], ['ca', 'jha', 'ma'], ['ca', 'ma', 'ra'], ['ca', 'ma', 'ttha'], ['ca', 'jha', 'ra'], ['ca', 'jha', 'ttha'], ['ca', 'ra', 'ttha'], ['bha', 'nya', 'va'], ['ma', 'nya', 'va'], ['jha', 'nya', 'va'], ['nya', 'ra', 'va'], ['nya', 'ttha', 'va'], ['bha', 'ma', 'nya'], ['bha', 'jha', 'nya'], ['bha', 'nya', 'ra'], ['bha', 'nya', 'ttha'], ['jha', 'ma', 'nya'], ['ma', 'nya', 'ra'], ['ma', 'nya', 'ttha'], ['jha', 'nya', 'ra'], ['jha', 'nya', 'ttha'], ['nya', 'ra', 'ttha'], ['bha', 'ma', 'va'], ['bha', 'jha', 'va'], ['bha', 'ra', 'va'], ['bha', 'ttha', 'va'], ['jha', 'ma', 'va'], ['ma', 'ra', 'va'], ['ma', 'ttha', 'va'], ['jha', 'ra', 'va'], ['jha', 'ttha', 'va'], ['ra', 'ttha', 'va'], ['bha', 'jha', 'ma'], ['bha', 'ma', 'ra'], ['bha', 'ma', 'ttha'], ['bha', 'jha', 'ra'], ['bha', 'jha', 'ttha'], ['bha', 'ra', 'ttha'], ['jha', 'ma', 'ra'], ['jha', 'ma', 'ttha'], ['ma', 'ra', 'ttha'], ['jha', 'ra', 'ttha']]] ,

// murty hindi devanagari: triplet combinations of ['da', 'ddha', 'nna', 'sha', 'ssa', 'ta', 'tha', 'ya'], total: 56
['murty-hindi_devanagari', 'https://getform.org/f/39d4d3af-9c1e-4744-b3fb-4ee7ae82c643', [['ddha', 'sha', 'tha'], ['ddha', 'ta', 'tha'], ['da', 'ddha', 'tha'], ['ddha', 'nna', 'tha'], ['ddha', 'ssa', 'tha'], ['ddha', 'tha', 'ya'], ['ddha', 'sha', 'ta'], ['da', 'ddha', 'sha'], ['ddha', 'nna', 'sha'], ['ddha', 'sha', 'ssa'], ['ddha', 'sha', 'ya'], ['da', 'ddha', 'ta'], ['ddha', 'nna', 'ta'], ['ddha', 'ssa', 'ta'], ['ddha', 'ta', 'ya'], ['da', 'ddha', 'nna'], ['da', 'ddha', 'ssa'], ['da', 'ddha', 'ya'], ['ddha', 'nna', 'ssa'], ['ddha', 'nna', 'ya'], ['ddha', 'ssa', 'ya'], ['sha', 'ta', 'tha'], ['da', 'sha', 'tha'], ['nna', 'sha', 'tha'], ['sha', 'ssa', 'tha'], ['sha', 'tha', 'ya'], ['da', 'ta', 'tha'], ['nna', 'ta', 'tha'], ['ssa', 'ta', 'tha'], ['ta', 'tha', 'ya'], ['da', 'nna', 'tha'], ['da', 'ssa', 'tha'], ['da', 'tha', 'ya'], ['nna', 'ssa', 'tha'], ['nna', 'tha', 'ya'], ['ssa', 'tha', 'ya'], ['da', 'sha', 'ta'], ['nna', 'sha', 'ta'], ['sha', 'ssa', 'ta'], ['sha', 'ta', 'ya'], ['da', 'nna', 'sha'], ['da', 'sha', 'ssa'], ['da', 'sha', 'ya'], ['nna', 'sha', 'ssa'], ['nna', 'sha', 'ya'], ['sha', 'ssa', 'ya'], ['da', 'nna', 'ta'], ['da', 'ssa', 'ta'], ['da', 'ta', 'ya'], ['nna', 'ssa', 'ta'], ['nna', 'ta', 'ya'], ['ssa', 'ta', 'ya'], ['da', 'nna', 'ssa'], ['da', 'nna', 'ya'], ['da', 'ssa', 'ya'], ['nna', 'ssa', 'ya']]] ,

// devanagari mt devanagari: triplet combinations of ['ca', 'cha', 'dda', 'dha', 'gha', 'ha', 'tta', 'u'], total: 56
['devanagari-mt_devanagari', 'https://getform.org/f/2c5147ca-d708-4974-9b81-efab47829ff7', [['cha', 'dha', 'u'], ['cha', 'dda', 'u'], ['cha', 'ha', 'u'], ['ca', 'cha', 'u'], ['cha', 'gha', 'u'], ['cha', 'tta', 'u'], ['dda', 'dha', 'u'], ['dha', 'ha', 'u'], ['ca', 'dha', 'u'], ['dha', 'gha', 'u'], ['dha', 'tta', 'u'], ['dda', 'ha', 'u'], ['ca', 'dda', 'u'], ['dda', 'gha', 'u'], ['dda', 'tta', 'u'], ['ca', 'ha', 'u'], ['gha', 'ha', 'u'], ['ha', 'tta', 'u'], ['ca', 'gha', 'u'], ['ca', 'tta', 'u'], ['gha', 'tta', 'u'], ['cha', 'dda', 'dha'], ['cha', 'dha', 'ha'], ['ca', 'cha', 'dha'], ['cha', 'dha', 'gha'], ['cha', 'dha', 'tta'], ['cha', 'dda', 'ha'], ['ca', 'cha', 'dda'], ['cha', 'dda', 'gha'], ['cha', 'dda', 'tta'], ['ca', 'cha', 'ha'], ['cha', 'gha', 'ha'], ['cha', 'ha', 'tta'], ['ca', 'cha', 'gha'], ['ca', 'cha', 'tta'], ['cha', 'gha', 'tta'], ['dda', 'dha', 'ha'], ['ca', 'dda', 'dha'], ['dda', 'dha', 'gha'], ['dda', 'dha', 'tta'], ['ca', 'dha', 'ha'], ['dha', 'gha', 'ha'], ['dha', 'ha', 'tta'], ['ca', 'dha', 'gha'], ['ca', 'dha', 'tta'], ['dha', 'gha', 'tta'], ['ca', 'dda', 'ha'], ['dda', 'gha', 'ha'], ['dda', 'ha', 'tta'], ['ca', 'dda', 'gha'], ['ca', 'dda', 'tta'], ['dda', 'gha', 'tta'], ['ca', 'gha', 'ha'], ['ca', 'ha', 'tta'], ['gha', 'ha', 'tta'], ['ca', 'gha', 'tta']]] ,

// kohinoor devanagari devanagari: triplet combinations of ['ba', 'dda', 'ga', 'ha', 'i', 'na', 'pa', 'sa'], total: 56
['kohinoor-devanagari_devanagari', 'https://getform.org/f/3ca6408c-6f76-41fe-a230-fd2bc9d0123a', [['dda', 'ha', 'i'], ['dda', 'ga', 'i'], ['dda', 'i', 'na'], ['dda', 'i', 'pa'], ['ba', 'dda', 'i'], ['dda', 'i', 'sa'], ['ga', 'ha', 'i'], ['ha', 'i', 'na'], ['ha', 'i', 'pa'], ['ba', 'ha', 'i'], ['ha', 'i', 'sa'], ['ga', 'i', 'na'], ['ga', 'i', 'pa'], ['ba', 'ga', 'i'], ['ga', 'i', 'sa'], ['i', 'na', 'pa'], ['ba', 'i', 'na'], ['i', 'na', 'sa'], ['ba', 'i', 'pa'], ['i', 'pa', 'sa'], ['ba', 'i', 'sa'], ['dda', 'ga', 'ha'], ['dda', 'ha', 'na'], ['dda', 'ha', 'pa'], ['ba', 'dda', 'ha'], ['dda', 'ha', 'sa'], ['dda', 'ga', 'na'], ['dda', 'ga', 'pa'], ['ba', 'dda', 'ga'], ['dda', 'ga', 'sa'], ['dda', 'na', 'pa'], ['ba', 'dda', 'na'], ['dda', 'na', 'sa'], ['ba', 'dda', 'pa'], ['dda', 'pa', 'sa'], ['ba', 'dda', 'sa'], ['ga', 'ha', 'na'], ['ga', 'ha', 'pa'], ['ba', 'ga', 'ha'], ['ga', 'ha', 'sa'], ['ha', 'na', 'pa'], ['ba', 'ha', 'na'], ['ha', 'na', 'sa'], ['ba', 'ha', 'pa'], ['ha', 'pa', 'sa'], ['ba', 'ha', 'sa'], ['ga', 'na', 'pa'], ['ba', 'ga', 'na'], ['ga', 'na', 'sa'], ['ba', 'ga', 'pa'], ['ga', 'pa', 'sa'], ['ba', 'ga', 'sa'], ['ba', 'na', 'pa'], ['na', 'pa', 'sa'], ['ba', 'na', 'sa'], ['ba', 'pa', 'sa']]] ,
];